### ISSUE TITLE
Instance of TestsWithErrorsException class did not understand #signalFor:

### ISSUE THREAD

**Issue by mabdi** [pavel-krivanek/mutalk#13]
I receive the error:

``Instance of TestsWithErrorsException class did not understand #signalFor:``

 when I run the tool on a test having a failing test method.

![image](https://user-images.githubusercontent.com/3696683/128699913-7e02d2fe-a640-44dd-b702-6afb32bc45c7.png)

## how to reproduce:
Add a red test to your test class like: 

```smalltalk
testAbort
	self deny: true
```

**Comment by pavel-krivanek** [comment]
looks like we can use just `signal` in this case. It fills `signaler` with `self`
