### ISSUE TITLE
Running the Metacello script in a Pharo 10 image produces an error

### ISSUE THREAD

**Issue by jordanmontt** [pavel-krivanek/mutalk#15]
Like we see in PharoDays, you cannot install the tool using the Metacello script in a Pharo 10 image. You need to do it manually

**Comment by jordanmontt** [comment]
This seems to be a problem with the baseline

**Comment by pavel-krivanek** [comment]
What error are you getting? I tested it in plain Pharo 10 (Build information: Pharo-10.0.0+build.421.sha.6e3a81cd8cc43707af3d762b9c590aff16b64acb (64 Bit)) without any issue

**Comment by pavel-krivanek** [comment]
For the tools. MuTalk-UI is there only for storing the old code which is not working. The GT integration cannot work in Pharo 10 because it was removed from the standard image.

**Comment by pavel-krivanek** [comment]
At least, I removed the code from readme...

**Comment by jordanmontt** [comment]
![Capture d’écran 2022-03-07 à 09 53 47](https://user-images.githubusercontent.com/33934979/156998930-ce361014-6ec5-4868-9e0c-529cdbbfb788.png)

I get this error

**Comment by pavel-krivanek** [comment]
I tried to explicitly define Pharo 10 in the readme. Can you try again on a fresh image with empty `pharo-local`, please?

**Comment by jordanmontt** [comment]
Yes, now works
