### ISSUE TITLE
How to lunch on new versions of Pharo

### ISSUE THREAD

**Issue by mabdi** [pavel-krivanek/mutalk#2]
Unfortunately, the image is not compatible with new versions of Pharo.

Could you please prepare us some instructions on:

- How to lunch mutalk on new versions of Pharo
- Or, How to get and run the Pharo version 1.1

Many thanks,

**Comment by pavel-krivanek** [comment]
What image? I'm not the original author of Mutalk. To run Pharo 1.1 you need the same VM as Squeak 3.9 has. 

The Mutalk is running in the very latest versions of Pharo, see the readme of this repository. However, the original UI is not working.

**Comment by mabdi** [comment]
My mistake.
I was loading original version from [http://www.squeaksource.com/MutationTesting](http://www.squeaksource.com/MutationTesting)
